project:
  type: website
  output-dir: docs

website:
  title: "Tim Wen Lingxuan Gao Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Final Project
        menu:
          - href: final_project/intro.qmd
            text: Introduction
          - href: final_project/data.qmd
            text: Data
          - href: final_project/methodology.qmd
            text: Methodology
          - href: final_project/results.qmd
            text: Results
          - href: final_project/conclusion.qmd
            text: Conclusion
      - text: Weekly Notes 

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto